### ISSUE TITLE
settings.json and trakt monitoring

### ISSUE THREAD

**Issue by mallah94** [itsToggle/plex_debrid#341] opened 2023-01-19 12:16 UTC
### Discussed in https://github.com/itsToggle/plex_debrid/discussions/320

<div type='discussions-op-text'>

<sup>Originally posted by **mallah94** January 14, 2023</sup>
Hello everyone! first of all thank you itsToggle for your work here! 

I recently pulled the newest docker image and restarted everything form scratch but for some reason I am now facing 2 problems (will elaborate on them a bit more down):
1- the container can't read an existing settings files, even starting from scratch and then restarting shows the same behaviour. 
2- after settings up and running I do reach "[trakt] getting entire trakt collection ... done" but then nothing more happens not matter what i update on the monitored trakt lists. 

My env:

1. Ubuntu server (vm)
2. docker.
3. rclone_rd mounted as docker volume
4. plex

I added the docker container exactly like the documentation asks with the addition of a restart flag: `docker run  -v /MY/path/to/config:/config --restart unless-stopped --net host -ti itstoggle/plex_debrid`

for point number 1 changing the following in main.py seems to fix the issue (please keep in mind that i have not read the full code so this was just a direct fix i immediately saw reading the first couple of lines in main if this is supposed to be handled somewhere else in code I apologize): 
`if os.path.exists('./settings.json'):
    if os.path.getsize('./settings.json') > 0 and os.path.isfile('./settings.json'):
        config_dir = "."`
to 
`if os.path.exists('./config/settings.json'):
    if os.path.getsize('./config/settings.json') > 0 and os.path.isfile('./config/settings.json'):
        config_dir = "./config"`

solved the issue

any help with problem 2 or knowledge if I am initializing the container wrong for problem 1

(forgot to mention but logs show nothing important)
</div>

**Comment by itsToggle** [comment] 2023-01-20 06:46
Could you tell me the exact path you are entering?

**Comment by mallah94** [comment] 2023-01-20 08:12
`/mnt/data/plexdebrid/Config`  , the writes of the path are good and again it was the path used before in a previous run .

**Comment by itsToggle** [comment] 2023-01-22 07:48
Hm I'm not sure where the problem is. The main.py code seems to work generally speaking, and the bit you adjusted is for backwards compatibility. I don't really want to touch that.
Currently, any "settings.json" file that is found in the root directory has priority over any settings file in the /config directory.

**Comment by itsToggle** [comment] 2023-01-22 08:46
regardding your trakt issue, have you actually added your watchlist to the monitored trakt lists?

**Comment by mallah94** [comment] 2023-01-22 10:01
@itsToggle yeah it's added to trakt, surprisingly Plex lists work fine, i am testing and it seems to maybe be related to a list that i emptied recently. Will test some more and confirm.

**Comment by itsToggle** [comment] 2023-01-22 10:16
Just to be clear, I ment have you added the list you want to monitor to the plex_debrid setting found at /Settings/Content Services/Trakt/lists/

**Comment by mallah94** [comment] 2023-01-22 10:35
Yeah it is added

**Comment by itsToggle** [comment] 2023-01-22 10:37
what type of content are you adding? only entire shows and movies are monitored.

**Comment by mallah94** [comment] 2023-01-23 13:21
so for the settings.json problem I really don't understand why its happening. for the trakt problem I still do not know the exact cause. With that in mind, I cleared all my lists and then added stuff back and the plex_debrid scanning worked again (assuming something was corrupt or wrong inside one of my lists.), so it seems like something went wrong in trakt and not in plex_debrid.

**Comment by itsToggle** [comment] 2023-01-23 15:10
`/mnt/data/plexdebrid/Config` - is this a directory or is `Config` a file?
I don't know what the issue could be. It works for everyone else it seems.

**Comment by mallah94** [comment] 2023-01-23 15:13
Config is a directory. 

@itsToggle  for the trakt issue it has to do with an empty collection! adding just 1 movie to the trakt collection (not watch list) fixes the issue

**Comment by itsToggle** [comment] 2023-01-25 07:58
Thats good to know, though I cant find the reason for this in the code.

I will be closing this issue now, as this seems to be something on your end. If you want to find out how others are setting up their plex_debrid docker containers, check or discord server :)

**Closed by itsToggle** 2023-01-25 07:58 UTC
Labels: bug
