### ISSUE TITLE
Issues scraping indexers from jackett

### ISSUE THREAD

**Issue by Bayharbourbutcher1** [itsToggle/plex_debrid#19] opened 2022-06-11 03:03 UTC
Hi there, here is the snip of the errors i a m getting when only jackett scraper is enabled. I have no issues using the default scrapers. Let me know if you need anything else. I am using a windows 10 machine.
![image](https://user-images.githubusercontent.com/107286599/173170160-d77c2877-c780-4671-99f7-7e6462f71e5c.png)

**Comment by Bayharbourbutcher1** [comment] 2022-06-11 03:04
![image](https://user-images.githubusercontent.com/107286599/173170230-e5e475e9-c9ca-49c5-9060-5595eb5d19a5.png)

**Comment by itsToggle** [comment] 2022-06-11 06:52
Oh thats a wierd one! Usually Jackett returns either a magnet directly (e.g. rarbg indexer) or it provides a link that redirects to a magnet (e.g. 1337x). It seems that one of your indexers does not redirect to a magnet. I should catch that exception. Could you tell me which indexers you got set up?

**Comment by Bayharbourbutcher1** [comment] 2022-06-11 06:59
![image](https://user-images.githubusercontent.com/107286599/173177283-18191232-1ca7-4f14-85a8-b6953665e622.png)
These are the indexers i have configured.

**Comment by itsToggle** [comment] 2022-06-12 06:52
Alright so the script will now catch the exception. I will try to find the root cause of the problem though. One of these indexers doesn't redirect to a magnet link in the way the others do, as I mentioned earlier. I'll keep this issue open until I fix the root cause of the problem, but you will be able to use Jackett now :)

**Comment by Bayharbourbutcher1** [comment] 2022-06-12 07:48
Thank you so much mate! Ill re-nable jackett again and test, will get back to you with the results.

**Comment by Bayharbourbutcher1** [comment] 2022-06-12 23:39
![image](https://user-images.githubusercontent.com/107286599/173258264-d20dda9c-3e68-49da-9dcc-1ef27d610975.png)
So i copied over your changes to the script and re-enabled jackett, now getting the above error, any ideas?

**Comment by itsToggle** [comment] 2022-06-13 07:23
alrighty, Ive added a catch for that exception aswell. This should never happen though, since plex should provide a release date for all listed seasons - and even if not, the object should absolutely have the attribute that the exception said was missing. would you mind telling me which show this was happening for?

**Comment by Bayharbourbutcher1** [comment] 2022-06-13 07:26
Hey thanks again for that! I am actually not sure which show this was for as i hadn't actually added anything new in the last 24 hours or so. Ill update the script now and test.

**Comment by itsToggle** [comment] 2022-06-13 07:30
Oh than it might have been a new season of a watchlisted show that plex added while the script was running? Not sure.

**Comment by Bayharbourbutcher1** [comment] 2022-06-13 07:51
![image](https://user-images.githubusercontent.com/107286599/173305697-5ee403f4-cce1-4ed0-8e64-014fcef26a72.png)
Another error, copied over the changes to the script and ran again.

**Comment by itsToggle** [comment] 2022-06-13 07:56
jesus im sorry, should be fixed now. Would you mind telling me which shows you have in the watchlist? It seems that one season of those shows is actually missing the release date, Id like to know what other attributes could be missing aswell :)

**Comment by Bayharbourbutcher1** [comment] 2022-06-13 08:04
![image](https://user-images.githubusercontent.com/107286599/173307874-f5377488-cf20-4e13-9a58-e16837f002e8.png)
Got the error again after updating the script but it has continued to run this time though.

**Comment by Bayharbourbutcher1** [comment] 2022-06-13 09:20
Fantastic - Thanks again, everything is working well now! Possible to add content size limit options in the config at all? I know i am getting a bit greedy now haha. Its just that sometime you dont want to add gigantic dolby vision 80gb rips which struggle to stream :)

**Comment by itsToggle** [comment] 2022-06-13 11:11
Not at all haha, I very much apprechiate the ideas. The current sorting of releases is based  on regex definitions. Ive looked into this before, and there is no easy way to write a size limit as a regex definition - so i might need to change up the release sorting a bit. This is a good excuse to make adding rules more intuitive aswell. I'll see what I can do :)

**Closed by itsToggle** 2022-06-13 11:11 UTC
